/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuyIndexRouteImport } from './routes/buy.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as OrdersCodeRouteImport } from './routes/orders.$code'
import { Route as GuidesGenshinImpactTopUpRouteImport } from './routes/guides.genshin-impact-top-up'
import { Route as BuySlugRouteImport } from './routes/buy.$slug'
import { Route as AdminSuppliersRouteImport } from './routes/admin/suppliers'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminAssistantRouteImport } from './routes/admin/assistant'
import { Route as ApiPublicNotifyOrderRouteImport } from './routes/api/public/notify-order'
import { Route as ApiPublicClaimAdminRouteImport } from './routes/api/public/claim-admin'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyIndexRoute = BuyIndexRouteImport.update({
  id: '/buy/',
  path: '/buy/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersCodeRoute = OrdersCodeRouteImport.update({
  id: '/orders/$code',
  path: '/orders/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesGenshinImpactTopUpRoute =
  GuidesGenshinImpactTopUpRouteImport.update({
    id: '/guides/genshin-impact-top-up',
    path: '/guides/genshin-impact-top-up',
    getParentRoute: () => rootRouteImport,
  } as any)
const BuySlugRoute = BuySlugRouteImport.update({
  id: '/buy/$slug',
  path: '/buy/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSuppliersRoute = AdminSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAssistantRoute = AdminAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiPublicNotifyOrderRoute = ApiPublicNotifyOrderRouteImport.update({
  id: '/api/public/notify-order',
  path: '/api/public/notify-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClaimAdminRoute = ApiPublicClaimAdminRouteImport.update({
  id: '/api/public/claim-admin',
  path: '/api/public/claim-admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/wallet': typeof WalletRoute
  '/admin/assistant': typeof AdminAssistantRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/buy/$slug': typeof BuySlugRoute
  '/guides/genshin-impact-top-up': typeof GuidesGenshinImpactTopUpRoute
  '/orders/$code': typeof OrdersCodeRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/buy/': typeof BuyIndexRoute
  '/api/public/claim-admin': typeof ApiPublicClaimAdminRoute
  '/api/public/notify-order': typeof ApiPublicNotifyOrderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/wallet': typeof WalletRoute
  '/admin/assistant': typeof AdminAssistantRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/buy/$slug': typeof BuySlugRoute
  '/guides/genshin-impact-top-up': typeof GuidesGenshinImpactTopUpRoute
  '/orders/$code': typeof OrdersCodeRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/buy': typeof BuyIndexRoute
  '/api/public/claim-admin': typeof ApiPublicClaimAdminRoute
  '/api/public/notify-order': typeof ApiPublicNotifyOrderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/wallet': typeof WalletRoute
  '/admin/assistant': typeof AdminAssistantRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/buy/$slug': typeof BuySlugRoute
  '/guides/genshin-impact-top-up': typeof GuidesGenshinImpactTopUpRoute
  '/orders/$code': typeof OrdersCodeRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/buy/': typeof BuyIndexRoute
  '/api/public/claim-admin': typeof ApiPublicClaimAdminRoute
  '/api/public/notify-order': typeof ApiPublicNotifyOrderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/track'
    | '/wallet'
    | '/admin/assistant'
    | '/admin/notifications'
    | '/admin/products'
    | '/admin/suppliers'
    | '/buy/$slug'
    | '/guides/genshin-impact-top-up'
    | '/orders/$code'
    | '/products/$slug'
    | '/admin/'
    | '/buy/'
    | '/api/public/claim-admin'
    | '/api/public/notify-order'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/track'
    | '/wallet'
    | '/admin/assistant'
    | '/admin/notifications'
    | '/admin/products'
    | '/admin/suppliers'
    | '/buy/$slug'
    | '/guides/genshin-impact-top-up'
    | '/orders/$code'
    | '/products/$slug'
    | '/admin'
    | '/buy'
    | '/api/public/claim-admin'
    | '/api/public/notify-order'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/track'
    | '/wallet'
    | '/admin/assistant'
    | '/admin/notifications'
    | '/admin/products'
    | '/admin/suppliers'
    | '/buy/$slug'
    | '/guides/genshin-impact-top-up'
    | '/orders/$code'
    | '/products/$slug'
    | '/admin/'
    | '/buy/'
    | '/api/public/claim-admin'
    | '/api/public/notify-order'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrackRoute: typeof TrackRoute
  WalletRoute: typeof WalletRoute
  BuySlugRoute: typeof BuySlugRoute
  GuidesGenshinImpactTopUpRoute: typeof GuidesGenshinImpactTopUpRoute
  OrdersCodeRoute: typeof OrdersCodeRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  BuyIndexRoute: typeof BuyIndexRoute
  ApiPublicClaimAdminRoute: typeof ApiPublicClaimAdminRoute
  ApiPublicNotifyOrderRoute: typeof ApiPublicNotifyOrderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/': {
      id: '/buy/'
      path: '/buy'
      fullPath: '/buy/'
      preLoaderRoute: typeof BuyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$code': {
      id: '/orders/$code'
      path: '/orders/$code'
      fullPath: '/orders/$code'
      preLoaderRoute: typeof OrdersCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/genshin-impact-top-up': {
      id: '/guides/genshin-impact-top-up'
      path: '/guides/genshin-impact-top-up'
      fullPath: '/guides/genshin-impact-top-up'
      preLoaderRoute: typeof GuidesGenshinImpactTopUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/$slug': {
      id: '/buy/$slug'
      path: '/buy/$slug'
      fullPath: '/buy/$slug'
      preLoaderRoute: typeof BuySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/suppliers': {
      id: '/admin/suppliers'
      path: '/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AdminSuppliersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/assistant': {
      id: '/admin/assistant'
      path: '/assistant'
      fullPath: '/admin/assistant'
      preLoaderRoute: typeof AdminAssistantRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/public/notify-order': {
      id: '/api/public/notify-order'
      path: '/api/public/notify-order'
      fullPath: '/api/public/notify-order'
      preLoaderRoute: typeof ApiPublicNotifyOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/claim-admin': {
      id: '/api/public/claim-admin'
      path: '/api/public/claim-admin'
      fullPath: '/api/public/claim-admin'
      preLoaderRoute: typeof ApiPublicClaimAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAssistantRoute: typeof AdminAssistantRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSuppliersRoute: typeof AdminSuppliersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAssistantRoute: AdminAssistantRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSuppliersRoute: AdminSuppliersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrackRoute: TrackRoute,
  WalletRoute: WalletRoute,
  BuySlugRoute: BuySlugRoute,
  GuidesGenshinImpactTopUpRoute: GuidesGenshinImpactTopUpRoute,
  OrdersCodeRoute: OrdersCodeRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  BuyIndexRoute: BuyIndexRoute,
  ApiPublicClaimAdminRoute: ApiPublicClaimAdminRoute,
  ApiPublicNotifyOrderRoute: ApiPublicNotifyOrderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
